# ==========================================
# CONFIGURACIÓN POR DEFECTO / PRODUCCIÓN (PostgreSQL)
# ==========================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=usuario_prod
quarkus.datasource.password=password_prod
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/db_empleados
quarkus.hibernate-orm.database.generation=validate

# ==========================================
# CONFIGURACIÓN DE DESARROLLO LOCAL (%dev) -> Usa H2
# ==========================================
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:empleados_db;DB_CLOSE_DELAY=-1

# Crea y actualiza las tablas automáticamente en H2 cada vez que guardas código
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
